development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: jabarta_development
  pool: 5
  username: tim
  password: 321321

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: jabarta_test
  pool: 5
  username: tim
  password: 321321